
dataset_config:
  name: "KITTI_"
  path: "../KITTI-MOTS/"

  train:
    labels_path: "instances_txt/"
    prefix: "training/image_02/"
    directories:
      - "0000"
      - "0001"
      - "0003"
      - "0004"
      - "0005"
      - "0009"
      - "0011"
      - "0012"
      - "0015"
      - "0017"
      - "0019"
      - "0020"
      - "0021"

  validation:
    labels_path: "instances_txt/"
    prefix: "training/image_02/"
    directories:
      - "0002"
      - "0006"
      - "0007"
      - "0008"
      - "0010"
      - "0013"
      - "0014"
      - "0016"
      - "0018"